### ISSUE TITLE
8b <--> 16b conversion

### ISSUE THREAD

**Issue by Floessie** [butcherg/gimage#1]
Hi Glenn,

I know this is only meant as study object, but as such it should be done most optimally, I think.

We had some discussion about about the 8b/16b conversion over at RawTherapee lately and came to a good conclusion on how this should be done correctly. If you like, see [PR 3432](https://github.com/Beep6581/RawTherapee/pull/3432).

Another thing, I'd like to mention as a long time C++ developer, is your use of `malloc()` instead of `new` (or even better a suitable container like `std::vector<>`) and passing big objects by value instead of `const &`. And in `gImage` I don't see a copy c'tor nor the prevention of an implicit one, which will definitely wreak havoc.

HTH
Flössie

**Comment by butcherg** [comment]
Flössie,

Thanks; I'm a recalcitrant C programmer, dragging myself kicking and screaming into C++...
1. I just committed the changes to new/delete; I'm wondering if this was the cause of malloc fails in Resize, where I was creating new gImages to do the shears.  Compelled me to change the pix struct from double to float.  Could it be that malloc/free in a C++ program get a "special" heap?
2. Now, the 8/16 bit conversions, is that essentially the rounding?  I really don't have any direct 8->16 bit conversions; all integral value bitmaps are converted to floating-point when a file is loaded, then converted back to integral 8 or 16bit upon saving.  So, I think what I need is to round the 0.0-255.0 floats when converting to either 8 or 16 bit integral values...
3. For the pass-by-value, I'm going to need to study the construct a bit...  
4. There is a Copy method, does that count?  :D

I'll keep the issue open until I've dispositioned all four things.

Thanks!

**Comment by Floessie** [comment]
Glenn,

> Thanks; I'm a recalcitrant C programmer, dragging myself kicking and screaming into C++...

You'll love it (in the **long** run). :wink: 

> I just committed the changes to new/delete; I'm wondering if this was the cause of malloc fails in Resize, where I was creating new gImages to do the shears. Compelled me to change the pix struct from double to float. Could it be that malloc/free in a C++ program get a "special" heap?

No, sorry. Maybe it works now, because you missed some `[]` with `delete contrib` and the like in `gImage::Resize()`. I know, when coming from C you love doing memory management the raw way, but do yourself a favor and use a proper container like `std::vector<>`. Or is there something else that prevents you from doing so?

> Now, the 8/16 bit conversions, is that essentially the rounding? I really don't have any direct 8->16 bit conversions; all integral value bitmaps are converted to floating-point when a file is loaded, then converted back to integral 8 or 16bit upon saving. So, I think what I need is to round the 0.0-255.0 floats when converting to either 8 or 16 bit integral values...

Yes, rounding a `/ 257` when going 8 bits and `* 257` when going 16 bits. I only raised this issue because of [this](https://github.com/butcherg/gimage/blob/master/gimage.cpp#L28).

BTW: What if someone passes `bits` as 15? Strange things might happen, probably hard to debug. And if `bits` is 0, you're leaking a lot of memory. So either `assert()` here or even better use an `enum` for `bits`.

> For the pass-by-value, I'm going to need to study the construct a bit... 

If you are seriously seeking for C++ basics, I can only recommend Scott Meyer's "Effective C++" books. The first two volumes should by now be reasonably cheap.

> There is a Copy method, does that count? :D

No.

Noone prevents your users to write somthing like:

```
gImage my_image = other_image;
```

After this, `my_image` and `other_image` will share `gImage::pix`, which later leads to segfaults.

Best
Flössie

**Comment by butcherg** [comment]
ooookay, there's now a cpp branch that I believe handles #1, #3, and #4.  You have dragged me over the line, I think I'm now thinking c++ more than c.  There are no more pointer allocation of gImage objects, it's all copy.  Since I converted the image data to std::vector<pix>, I didn't write a copy constructor, but I'll probably have to when I incorporate ICC profiles from LCMS.  

Hurts my head a little, but I did an exercise with vectors today to see how they perform against raw access.  With no optimization, vector took twice as long.  'With -O2, it came down to a few tens of milliseconds, and with -O3 it became equivalent in speed.  That, and reading up on the object memory management of C++ and I'm ready to dump *.

The contrib data structures in Resize are still new/delete, but I added the [] to the destructors.  I copied that code from the Programming Gems public domain code, so I need to think it through first.  Also, I messed with the rounding a bit but I'm probably too tired to get the typecasting in the expression correct.  I'll try to complete these things tomorrow, test a bit (I've already run a raw image through the chain to a brightened/denoised/resized/sharpened JPEG, worked just fine), and then merge to master.

I was going to defer doing this until I'd incorporated gimage into rawproc, but decided that it was easier to figure out with the command line program than mixing those changes with wxWidgets right from the start.  Flössie, thanks for pushing me; I guess I can still learn new things approaching 60 years... 

g

**Comment by Floessie** [comment]
Glenn,

This looks much better! :tada: It's not perfect yet, but that's a good start.

> You have dragged me over the line, I think I'm now thinking c++ more than c.

Great to here that. :smiley: 

> Hurts my head a little, but I did an exercise with vectors today to see how they perform against raw access. With no optimization, vector took twice as long. 'With -O2, it came down to a few tens of milliseconds, and with -O3 it became equivalent in speed. That, and reading up on the object memory management of C++ and I'm ready to dump *.

That's to be expected, since you index for each access to `pix::r`, `pix::g`, and `pix::b`. Without optimization this will be a call to `std::vector<pix>::operator []()`. There are two things, you can try:
- Grab a `pix&` for the three accesses, like `pix& p = dst[pos];`. Don't know, if this is really faster without `-O`, but could be worth a try.
- Iterate over the lines using an iterator where feasible, like `std::vector<pix>::iterator pos = image.begin()`.

Anyway, as this whole problem is usually optimized away, I wouldn't spend too much time on it.

When you've progressed a bit further with you C++ experiments, there will be the point when you'll move on to C++11 for its smart pointers. A `std::unique_ptr<char>` would be handy for `char *getImageData(BPP bits)`.

> I was going to defer doing this until I'd incorporated gimage into rawproc, but decided that it was easier to figure out with the command line program than mixing those changes with wxWidgets right from the start. 

Sounds like a sane plan. It's always good to have a playground before turning over to more serious business.

> Flössie, thanks for pushing me; I guess I can still learn new things approaching 60 years...

Absolutely. I've only just familiarized myself with C++11, it's lifelong learing. And I didn't mean to stress you. There were some beginner's mistakes, I was urged to comment on. The Meyer's books are really nice and fun to read.

Best
Flössie

**Comment by butcherg** [comment]
So, I finally dealt with the float->integer conversion, in conjunction with making it run less than 3 seconds for 16MP images.  My rawproc program uses this conversion for display, so it was making itself quite visible.  I didn't know this, but float->integer conversions are quite onerous compared to simple rounding; thanks http://www.agner.org/optimize/. So now, the conversions are done using the gnu g++ lrint(), which on my Windows 7 laptop I found to be just slightly faster than plain round().

I also had fun in rawproc with "reseatability".  With dynamically-allocated FreeImage constructs, this became a cornerstone of rawproc's incremental processing; changing a parameter in a tool only had to be processed forward in the chain.  Initially, I was attempting to reassign references to new object instances; that seemed to work until I crashed one run and discovered I'd allocated and not freed up about 1GB RAM.  I almost reverted back to pointers and new/delete until I thought through using the containers.  Now I'm using a deque<gImage> in my PicProcessor base class with setdib() and getdib() methods (dib is a holdover term from FreeImage) where set pushes the new object on the front and pops the previous one (and any other remaining) off the back, and get just gets the front.  Doing this resulted in surprisingly very little change to the rest of the program, mostly thanks to using PicProcessor as a base class for all the other tools, and so far has not seemed to introduce unwanted side effects.

All my malloc/frees are gone, and the only new/deletes are with regard to interfacing with the image libraries and the resize algorithm from Graphics Gems which I think I'll leave as-is for the time being  Bit-by-bit, so to speak, everywhere else I've changed my fundamental thinking to C++.

Funny, I've taken some of this thinking to work, which is about critical control applications, but I'm not ready to move forward yet until I understand more about what the compiler is doing.  Maybe it's my age-honed cynicism, but anything I perceive as "middleware" is just fodder for some fault tree I may have to work in the future.  And my definition of middleware does include compilers :D

Flössie, thanks for the push.  After the first of the new year, I intend to dig more comprehensively into the language with the Effective C++ books, many upcoming airplane trips to provide time.

**Comment by Floessie** [comment]
> Maybe it's my age-honed cynicism, but anything I perceive as "middleware" is just fodder for some fault tree I may have to work in the future. And my definition of middleware does include compilers :D

Well, I did mostly assembler programming when I was younger, and when I turned to higher level languages, I often blamed the compiler for doing something wrong, but in the end it was always me who relied on "undefined behavior". So from my experience, you can put some trust into the toolchain. :smile:
